server:
  port: 8080
  servlet:
    context-path: /

spring:
  # todo ?? ?????? ??
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true # ???? sql ??
    properties:
      hibernate:
        format_sql: true # sql?? ??? ??
        default_batch_fetch_size: 500 # ??? ??? ?? ? ?? ???
    open-in-view: false # ??? ????? ?? ??? ???? ??? ??

  servlet:
    multipart:
      max-file-size: 10MB # ?? ??? ?? ? ??? ?? ??? 10MB ??
      max-request-size: 100MB # ?? ??? ?? ? ?? ?? ???? 100MB ??

logging:
  level:
    org.hiberante.type: trace # ???? ??? ??? ?? ? ? ?? ?? ??

